# Generated by Django 4.2.3 on 2023-07-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('EstadoID', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.TextField(max_length=255)),
                ('TotalPesq', models.IntegerField(default=0)),
            ],
        ),
    ]
