# Generated by Django 4.2.3 on 2023-07-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_procu_comida', '0004_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estados',
            table='Estados',
        ),
    ]
